// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: calculator/pb/calculator.proto

package calculatorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	// for sum
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	// for server streaming
	SumStreaming(ctx context.Context, in *SumOneRequest, opts ...grpc.CallOption) (CalculatorService_SumStreamingClient, error)
	// for client streaming
	SumCStreaming(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_SumCStreamingClient, error)
	// for average streaming
	AverageService(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_AverageServiceClient, error)
}

type calculatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorServiceClient(cc grpc.ClientConnInterface) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculatorService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) SumStreaming(ctx context.Context, in *SumOneRequest, opts ...grpc.CallOption) (CalculatorService_SumStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[0], "/calculator.CalculatorService/SumStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceSumStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_SumStreamingClient interface {
	Recv() (*SumManyResponse, error)
	grpc.ClientStream
}

type calculatorServiceSumStreamingClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceSumStreamingClient) Recv() (*SumManyResponse, error) {
	m := new(SumManyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) SumCStreaming(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_SumCStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[1], "/calculator.CalculatorService/SumCStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceSumCStreamingClient{stream}
	return x, nil
}

type CalculatorService_SumCStreamingClient interface {
	Send(*SumManyRequest) error
	CloseAndRecv() (*SumOneResponse, error)
	grpc.ClientStream
}

type calculatorServiceSumCStreamingClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceSumCStreamingClient) Send(m *SumManyRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceSumCStreamingClient) CloseAndRecv() (*SumOneResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SumOneResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) AverageService(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_AverageServiceClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[2], "/calculator.CalculatorService/AverageService", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceAverageServiceClient{stream}
	return x, nil
}

type CalculatorService_AverageServiceClient interface {
	Send(*AverageRequest) error
	CloseAndRecv() (*AverageResponse, error)
	grpc.ClientStream
}

type calculatorServiceAverageServiceClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceAverageServiceClient) Send(m *AverageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceAverageServiceClient) CloseAndRecv() (*AverageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AverageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
// All implementations must embed UnimplementedCalculatorServiceServer
// for forward compatibility
type CalculatorServiceServer interface {
	// for sum
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	// for server streaming
	SumStreaming(*SumOneRequest, CalculatorService_SumStreamingServer) error
	// for client streaming
	SumCStreaming(CalculatorService_SumCStreamingServer) error
	// for average streaming
	AverageService(CalculatorService_AverageServiceServer) error
	mustEmbedUnimplementedCalculatorServiceServer()
}

// UnimplementedCalculatorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCalculatorServiceServer struct {
}

func (UnimplementedCalculatorServiceServer) Sum(context.Context, *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedCalculatorServiceServer) SumStreaming(*SumOneRequest, CalculatorService_SumStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method SumStreaming not implemented")
}
func (UnimplementedCalculatorServiceServer) SumCStreaming(CalculatorService_SumCStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method SumCStreaming not implemented")
}
func (UnimplementedCalculatorServiceServer) AverageService(CalculatorService_AverageServiceServer) error {
	return status.Errorf(codes.Unimplemented, "method AverageService not implemented")
}
func (UnimplementedCalculatorServiceServer) mustEmbedUnimplementedCalculatorServiceServer() {}

// UnsafeCalculatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalculatorServiceServer will
// result in compilation errors.
type UnsafeCalculatorServiceServer interface {
	mustEmbedUnimplementedCalculatorServiceServer()
}

func RegisterCalculatorServiceServer(s grpc.ServiceRegistrar, srv CalculatorServiceServer) {
	s.RegisterService(&CalculatorService_ServiceDesc, srv)
}

func _CalculatorService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_SumStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SumOneRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).SumStreaming(m, &calculatorServiceSumStreamingServer{stream})
}

type CalculatorService_SumStreamingServer interface {
	Send(*SumManyResponse) error
	grpc.ServerStream
}

type calculatorServiceSumStreamingServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceSumStreamingServer) Send(m *SumManyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CalculatorService_SumCStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).SumCStreaming(&calculatorServiceSumCStreamingServer{stream})
}

type CalculatorService_SumCStreamingServer interface {
	SendAndClose(*SumOneResponse) error
	Recv() (*SumManyRequest, error)
	grpc.ServerStream
}

type calculatorServiceSumCStreamingServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceSumCStreamingServer) SendAndClose(m *SumOneResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceSumCStreamingServer) Recv() (*SumManyRequest, error) {
	m := new(SumManyRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CalculatorService_AverageService_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).AverageService(&calculatorServiceAverageServiceServer{stream})
}

type CalculatorService_AverageServiceServer interface {
	SendAndClose(*AverageResponse) error
	Recv() (*AverageRequest, error)
	grpc.ServerStream
}

type calculatorServiceAverageServiceServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceAverageServiceServer) SendAndClose(m *AverageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceAverageServiceServer) Recv() (*AverageRequest, error) {
	m := new(AverageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorService_ServiceDesc is the grpc.ServiceDesc for CalculatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalculatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CalculatorService_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SumStreaming",
			Handler:       _CalculatorService_SumStreaming_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SumCStreaming",
			Handler:       _CalculatorService_SumCStreaming_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "AverageService",
			Handler:       _CalculatorService_AverageService_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "calculator/pb/calculator.proto",
}
